repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: python-ruff-format
        name: "python: ruff format"
        entry: uv run ruff format python
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: python-ruff-check
        name: "python: ruff check --fix"
        entry: uv run ruff check --fix python
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: python-pytest
        name: "python: pytest"
        entry: uv run pytest
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: rust-cargo-fmt
        name: "rust: cargo fmt --check"
        entry: cargo fmt --all --check
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: rust-cargo-check
        name: "rust: cargo check"
        entry: cargo check --all-targets --all-features
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: rust-cargo-build
        name: "rust: cargo build"
        entry: cargo build --all-targets --all-features
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: rust-cargo-udeps
        name: "rust: cargo udeps"
        entry: cargo +nightly udeps --all-targets --all-features
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: rust-cargo-clippy
        name: "rust: cargo clippy"
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: rust-cargo-test
        name: "rust: cargo test"
        entry: cargo test --all-features
        language: system
        pass_filenames: false
        stages: [pre-commit]
